### PR TITLE
10.0 smangukiya 13344 duplicate product configurator

### PR DESCRIPTION
**Pull request by smangukiya**
related task 13344
New module name: product_configurator_duplicate

### CODE REVIEW

**Comment by max3903** [comment]
@smangukiya 

When I run the configuration wizard in the backend for the duplicate, I get all the attributes on all the steps, even if the configuration looks correct. It's working perfectly on the website...

step1

step2

configuration

Do you have the same behavior? Can you fix it? Thanks!

**Comment by max3903** [comment]
Otherwise, everything else works as expected :+1:

**Comment by smangukiya** [comment]
@max3903 : Yes, this is interesting. Let me check.

**Comment by smangukiya** [comment]
@max3903 : Please review it again, it works fine now. Thanks!

**Comment by max3903** [comment]
@smangukiya Perfect. Great job! :+1:

**Pull request merged**
